SwiftRent/Controllers/RentController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using SwiftRent.Models;
using System.Data.Entity;

namespace SwiftRent.Controllers
{
    public class RentController : Controller
    {
        SwiftRentEntities db = new SwiftRentEntities();
        //
        // GET: Rent
        public ActionResult Index()
        {
            var Result = (from r in db.Rentals
                          join c in db.Carregs on r.CarId equals c.CarNo
                          select new RentalViewModel
                          {
                              Id = r.Id,
                              CarId = r.CarId,
                              CustId = r.CustId,
                              Fee = r.Fee,
                              StartDate = r.StartDate,
                              EndDate = r.EndDate,
                              Available = c.Available
                          }).ToList();

            return View(Result);
        }

        [HttpGet]
        public ActionResult GetCar()
        {
            try
            {
                var car = db.Carregs.ToList();
                return Json(car, JsonRequestBehavior.AllowGet);
            }
            catch (Exception ex)
            {
                // Log or handle the exception
                return Json(new { error = ex.Message }, JsonRequestBehavior.AllowGet);
            }
        }

        [HttpPost]
        public ActionResult GetId(int id)
        {
            try
            {
                var CustomerName = (from s in db.Customers where s.Id == id select s.CustName).ToList();
                return Json(CustomerName, JsonRequestBehavior.AllowGet);
            }
            catch (Exception ex)
            {
                // Log or handle the exception
                return Json(new { error = ex.Message }, JsonRequestBehavior.AllowGet);
            }
        }

        [HttpPost]
        public ActionResult GetName(string Name)
        {
            try
            {
                var CustomerId = (from s in db.Customers where s.CustName == Name select s.Id).ToList();
                return Json(CustomerId, JsonRequestBehavior.AllowGet);
            }
            catch (Exception ex)
            {
                // Log or handle the exception
                return Json(new { error = ex.Message }, JsonRequestBehavior.AllowGet);
            }
        }

        [HttpPost]
        public ActionResult GetAvil(string CarNo)
        {
            try
            {
                var CarAvil = (from s in db.Carregs where s.CarNo == CarNo select s.Available).FirstOrDefault();
                return Json(CarAvil, JsonRequestBehavior.AllowGet);
            }
            catch (Exception ex)
            {
                // Log or handle the exception
                return Json(new { error = ex.Message }, JsonRequestBehavior.AllowGet);
            }
        }

        [HttpPost]
        public ActionResult Save(Rental rent)
        {
            if (ModelState.IsValid)
            {
                db.Rentals.Add(rent);

                var Car = db.Carregs.SingleOrDefault(name => name.CarNo == rent.CarId);
                if (Car == null)
                    return HttpNotFound("CarNo Is Not Found");

                Car.Available = "No";
                db.Entry(Car).State = System.Data.Entity.EntityState.Modified;
                db.SaveChanges();
                return RedirectToAction("Index");
            }

            return View(rent);
        }

    }
}

SwiftRent/Controllers/ReturnCarController.cs
using SwiftRent.Models;
using System;
using System.Linq;
using System.Web.Mvc;
using System.Data.Entity;
using System.Data.Entity.SqlServer;

namespace SwiftRent.Controllers
{
    public class ReturnCarController : Controller
    {
        SwiftRentEntities db = new SwiftRentEntities();

        public ActionResult ReturnCar_index()
        {
            var ReturnCar = (from r in db.ReturnCars
                             join c in db.Carregs on r.CarNo equals c.CarNo
                             select new ReturnCarViewModel
                             {
                                 Id = r.Id,
                                 CarNo = r.CarNo,
                                 ReturnDate = r.ReturnDate,
                                 Elsp = r.Elsp /*?? 0*/,
                                 Fine = r.Fine /*?? 0*/,
                                 Available = c.Available
                             }).ToList();

            return View(ReturnCar);
        }

        [HttpGet]
        public ActionResult GetCar()
        {
            var car = db.Carregs.ToList();
            return Json(car, JsonRequestBehavior.AllowGet);
        }

        [HttpPost]
        public ActionResult GetData(string CarNo)
        {
            var CarNum = (from s in db.Rentals
                          where s.CarId == CarNo
                          select new
                          {
                              StartDate = s.StartDate,
                              EndDate = s.EndDate,
                              CustId = s.CustId,
                              CarNo = s.CarId,
                              Fee = s.Fee,
                              ExpiredDays = SqlFunctions.DateDiff("day", s.EndDate, s.StartDate)
                          }).ToArray();
            return Json(CarNum, JsonRequestBehavior.AllowGet);
        }

        [HttpPost]
        public ActionResult GetAvil(string CarNo)
        {
            try
            {
                var CarAvil = (from s in db.Carregs where s.CarNo == CarNo select s.Available).FirstOrDefault();
                return Json(CarAvil, JsonRequestBehavior.AllowGet);
            }
            catch (Exception ex)
            {
                // Log or handle the exception
                return Json(new { error = ex.Message }, JsonRequestBehavior.AllowGet);
            }
        }

        [HttpPost]
        public ActionResult Save(ReturnCarViewModel Returned)
        {
            if (ModelState.IsValid)
            {
                using (var transaction = db.Database.BeginTransaction())
                {
                    try
                    {
                        // Save returned car information
                        var returnedCar = new ReturnCar
                        {
                            CarNo = Returned.CarNo,
                            ReturnDate = Returned.ReturnDate,
                            Elsp = Returned.Elsp,
                            Fine = Returned.Fine
                        };

                        db.ReturnCars.Add(returnedCar);

                        // Update Carregs
                        var car = db.Carregs.SingleOrDefault(e => e.CarNo == Returned.CarNo);
                        if (car == null)
                        {
                            TempData["ErrorMessage"] = "Car not found";
                            return RedirectToAction("Index");
                        }

                        car.Available = "Yes";
                        db.Entry(car).State = EntityState.Modified;

                        db.SaveChanges();
                        transaction.Commit();

                        // Return a success message with a 200 status code
                        return Json(new { success = true, message = "Data saved successfully" });
                    }
                    catch (Exception ex)
                    {
                        transaction.Rollback();
                        TempData["ErrorMessage"] = "Error saving data: " + ex.Message;
                    }
                }
            }

            // If ModelState is not valid, return to the view with validation errors
            return Json(new { success = false, message = "Error saving data. Please try again." });
        }


    }
}

SwiftRent/Controllers/UserController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using System.Web.Security;
using SwiftRent.Models;

namespace SwiftRent.Controllers
{
    public class UserController : Controller
    {
        SwiftRentEntities db = new SwiftRentEntities();
        // GET: Userticket
        public ActionResult Login()
        {
            return View();
        }
        [HttpPost]
        public ActionResult Login(UserDetail user)
        {
            if (ModelState.IsValid)
            {
                bool IsValid = db.UserDetails.Any(u => u.Username == user.Username && u.Password == user.Password);
                if (IsValid)
                {
                    FormsAuthentication.SetAuthCookie(user.Username, false);
                    return RedirectToAction("Index", "Home");
                }
                else
                {
                    ViewBag.Message = "User Name or Password Invalid";
                    return View();
                }
            }
            return View();
        }

        public ActionResult Register()
        {
            ViewBag.RoleId = new SelectList(db.RoleDetails, "RoleId", "RoleName");
            return View();
        }

        [HttpPost]
        public ActionResult Register(UserDetail user)
        {
            if (ModelState.IsValid)
            {
                ViewBag.RoleId = new SelectList(db.RoleDetails, "RoleId", "RoleName");
                db.UserDetails.Add(user);
                db.SaveChanges();
                return RedirectToAction("Index", "Home");
            }
            return View();
        }

        public ActionResult Signout()
        {
            FormsAuthentication.SignOut();
            return RedirectToAction("Login");
        }
    }
}

SwiftRent/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>SwiftRent</title>
    @Styles.Render("~/Content/css")    
    <link href="~/Content/Layout.css" rel="stylesheet" />
    <link rel="shortcut icon" href="~/Content/image/logo.png" />
    @Scripts.Render("~/bundles/modernizr")
</head>
<body>
    <div class="navbar navbar-inverse navbar-fixed-top">
        <div class="container">
            <div class="navbar-header">
                <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                </button>
                <a class="navbar-brand" href="@Url.Action("Index", "Home")">
                    <img src="~/Content/image/logo.png" alt="Logo" />
                </a>
            </div>
            <div class="navbar-collapse collapse">
                <ul class="nav navbar-nav">
                    <li>
                        @if (User.Identity.IsAuthenticated)
                        {
                            @Html.ActionLink("Car", "Index", "Car")
                        }
                        else
                        {
                            @Html.ActionLink("Car", "Login", "User")
                        }
                    </li>
                    <li>
                        @if (User.Identity.IsAuthenticated)
                        {
                            @Html.ActionLink("Customer", "Index", "Customer")
                        }
                        else
                        {
                            @Html.ActionLink("Customer", "Login", "User")
                        }
                    </li>
                    <li>@Html.ActionLink("Rental", "Index", "Rent")</li>
                    <li>@Html.ActionLink("Return", "ReturnCar_index", "ReturnCar")</li>
                    <li>
                        @if (User.Identity.IsAuthenticated)
                        {
                            @Html.ActionLink("Report", "Index", "Report")
                        }
                        else
                        {
                            @Html.ActionLink("Report", "Login", "User")
                        }
                    </li>
                </ul>
                <ul class="nav navbar-nav navbar-right">
                    <li>@Html.ActionLink("Register", "Register", "User")</li>
                    @if (User.Identity.IsAuthenticated == false)
                    {
                        <li>@Html.ActionLink("Login", "Login", "User")</li>
                    }
                    @if (User.Identity.IsAuthenticated)
                    {
                        <li>
                            @Html.ActionLink("Logoff", "Signout", "User")
                        </li>
                    }
                </ul>
            </div>
        </div>
    </div>
    <div style="margin-left: 20px; margin-right: 20px; position: relative; min-height: 100vh;">
        @RenderBody()
        <footer style="position: absolute; bottom: 0; width: 100%;">
            <p>&copy; @DateTime.Now.Year - My ASP.NET Application</p>
        </footer>
    </div>




    @Scripts.Render("~/bundles/jquery")
    @Scripts.Render("~/bundles/bootstrap")
    @RenderSection("scripts", required: false)
</body>
</html>